language: node_js
node_js:
  - 10


notifications:
  webhooks: http://aubworks.com/notifications
  on_success: always # default: always
  on_failure: never # default: always
  on_start:   never # default: never
  on_cancel:  never # default: always
  on_error:   never # default: always
